package com.kh.practice;

import java.security.PublicKey;
import java.util.InputMismatchException;
import java.util.Iterator;
import java.util.Scanner;

public class ExceptionRun {

	public static void main(String[] args) {
	
		
		
		
		/* 1. ArithmeticException, InputMismatchException 
		 *  사용자로부터 2개의 정수를 입력 받고,
		 *  첫번째 입력된 값이 두번째 입력된 값의 배수인지 확인하여 
		 *  배수인 경우에은 "x은 x의 배수입니다." 출력 
		 *  배수가 아닌 경우에는 "x은 x의 배수가 아닙니다." 출력
		 *  (프로그램이 정상적으로 종료될 수 있도록 시작지점에 "--------start------")
		 *               				마지막 지점에 "--------end------"
		 */
		
	
		// exceptionTest1();
		exceptionTest2();
		
		
		
	
		
	}		
	
	public static void exceptionTest1() {
		Scanner sc = new Scanner(System.in);
		
		System.out.println("-------start----------");
		try 
		{
			System.out.print("정수 1 : " );
			int num1 = sc.nextInt(); 
			System.out.print("정수 2 : " );
			int num2 = sc.nextInt();
			
			if(num1 % num2 == 0  ) { //  ArithmeticException java.lang 경로에 있어서 import 생략
				System.out.println(num1 + "은" + num2 + "의 배수입니다" );
			}else {
				System.out.println("배수가 아닙니다");
			}
		}   // InputMismatchException util 경로에 있어 import 필요
		    catch (ArithmeticException | InputMismatchException e) {
				e.printStackTrace();
			}
		
		System.out.println("-------end------");
	}
	
	/* NegativeArraySizeException,  ArrayIndexOutOfBoundsException
	 * -5 ~ 5 사이의 난수를 발생시켜 해당 난수 크기로 배열을 생성한 후에 
	 * 1부터 배열 크기만큼 1씩 증가시키면서 값을 저장한 후 출력 
	 * (프로그램이 정상적으로 종료되는 것을 확인하기 위해 처음과 끝에 "start", "end" 출력)
	 * 
	 */
	
	
	public static void exceptionTest2() {
		
		
		Scanner sc = new Scanner(System.in);
		
		System.out.println("-------start----------");
		
		try {
		int num = sc.nextInt();
		int[] arr = new int[num];
		
		for(int i = 0; i < arr.length; i++) {
			arr[i] +=  (Math.round(i) + 1 );
			System.out.print(arr[i] + " ");
		}
		System.out.println();
		
	
	 } catch(NegativeArraySizeException | ArrayIndexOutOfBoundsException e) {
		 e.printStackTrace();
		 
	 }
	
	System.out.println("-------end------");
}
			
}
